model_list:
#OpenAI Models
  - model_name: openai/gpt-4o
    litellm_params:
      model: openai/gpt-4o

  - model_name: openai/gpt-4o-mini
    litellm_params:
      model: openai/gpt-4o-mini

  - model_name: openai/o3-mini
    litellm_params:
      model: openai/o3-mini

  - model_name: openai/gpt-4.1
    litellm_params:
      model: openai/gpt-4.1

#Google Gemini Models
  - model_name: gemini/gemini-2.5-flash
    litellm_params:
      model: gemini/gemini-2.5-flash

  - model_name: gemini/gemini-2.5-pro
    litellm_params:
      model: gemini/gemini-2.5-pro
    
#Bedrock Anthropic Models
  - model_name: bedrock/anthropic.claude-37-sonnet
    model_info:
        supports_vision: True
        supports_reasoning: True
        supports_prompt_caching: True
    litellm_params:
      model: bedrock/anthropic.claude-37-sonnet
      allowedModels: 
        - "anthropic.claude-37-sonnet"
      anthropic_version: bedrock-2023-05-31
      max_retries: 3 
      metadata:
        model_group: amazon-bedrock

  - model_name: bedrock/anthropic.claude-4-sonnet
    model_info:
        supports_vision: True
        supports_reasoning: True
        supports_prompt_caching: True
    custom_llm_provider: anthropic
    litellm_params:
      model: bedrock/anthropic.claude-4-sonnet
      allowedModels: 
        - "anthropic.claude-4-sonnet"
      anthropic_version: bedrock-2023-05-31
      max_retries: 3 
      metadata:
        model_group: amazon-bedrock


#Azure Foundry Models
  - model_name: azure_ai/DeepSeek-R1
    litellm_params:
      model: azure_ai/DeepSeek-R1

  - model_name: azure_ai/grok-3
    litellm_params:
      model: azure_ai/grok-3

  - model_name: azure_ai/Phi-4
    litellm_params:
      model: azure_ai/Phi-4



litellm_settings:
  drop_params: true
  callbacks: custom_callbacks.proxy_handler_instance

router_settings:
  model_group_alias: { 
    "claude-3-7-sonnet-latest": "bedrock/anthropic.claude-37-sonnet",
  }
